name: Docs to PDF

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  converttopdf:

    name: Build PDF

    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}


    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert to html
        run: sh entrypoint.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

