name: Docs to PDF

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
      - main

    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'docs/**.md'
      - 'docs/images/**'

jobs:
  converttopdf:

    name: Build PDF

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      # roba io
        
      - uses: actions/upload-artifact@v1
        
        with:
          name: docs
          path: pdfs