name: Docs to PDF

on: push

jobs:
  converttopdf:

    name: Build PDF

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - run: sh entrypoint.sh

      - uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./build/bundle.html
          outputFile: ./build/bundle.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: pdfs
